create table if not exists portfolio_items (
  id bigint generated by default as identity primary key,
  section text not null check (section in ('profile', 'timeline', 'project')),
  name text not null,
  tag text,
  description text,
  created_at timestamptz default now()
);

alter table portfolio_items enable row level security;

create policy "allow read portfolio items"
on portfolio_items for select
using (true);

create policy "allow insert portfolio items"
on portfolio_items for insert
with check (true);

create policy "allow delete portfolio items"
on portfolio_items for delete
using (true);
